name: First Workflow
on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string
      goodbye:
        required: true
        type: string
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }} / ${{ inputs.goodbye }}"
